access_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJiOWE1NTg1OWM1MTg0ZDEzOGRhYjhkY2VkM2ZhZTdjNSIsImlhdCI6MTY4NzQ0ODU0MywiZXhwIjoyMDAyODA4NTQzfQ.WOyWjyeyLSMBtWlMeoapOjXDPfBsOI4yBvN2TEDoLNU"
raspberry_ip = "http://raspberrypi.local:8123"
entity_id = "climate.air_conditioner_studio"
